services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: retinopathy-base
    container_name: retinopathy-dev
    volumes:
      - .:/app
    working_dir: /app
    tty: true

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: retinopathy-base
    container_name: retinopathy-app
    volumes:
      - .:/app
    working_dir: /app
    tty: true
